### ISSUE TITLE
Mincemeat

### ISSUE THREAD

**Issue by bondarevts** [bondarevts/mltran#3]
```
$ mltran mincemeat
Traceback (most recent call last):
  File ".../mltran/mltran.py", line 341, in <module>
    main()
  File ".../mltran/mltran.py", line 335, in main
    show_translations(phrase)
  File ".../mltran/mltran.py", line 81, in show_translations
    translations = translate(phrase)
  File ".../mltran/mltran.py", line 87, in translate
    return list(parse_translation_page(page_content))
  File ".../mltran/mltran.py", line 111, in parse_translation_page
    yield parse_translation(rows)
  File ".../mltran/mltran.py", line 125, in parse_translation
    header=parse_translation_header(rows.popleft()),
  File ".../mltran/mltran.py", line 141, in parse_translation_header
    assert translation_header_element is not None
AssertionError
```

**Comment by scrapix** [comment]
current version https://github.com/scrapix/multitran-cli

**Comment by bondarevts** [comment]
Nice!
